import type { ContentItem } from '../../types/content.ts';

export const experience: ContentItem[] = [
  {
    id: 'extuitive',
    title: 'Machine Learning Engineer II, Founding Team',
    subtitle: 'Extuitive / Flagship Pioneering',
    location: 'Boston, MA',
    period: 'Jun 2025 - Jun 2026',
    rating: 'Primary Role',
    tags: [
      'LangGraph',
      'TypeScript',
      'Next.js',
      'React',
      'Node.js',
      'Supabase',
      'Postgres',
      'Inngest',
      'AWS Lambda',
      'Stripe',
      'Anrok',
      'Meta API',
      'Shopify',
      'HubSpot',
      'Sentry',
      'PostHog',
    ],
    summary:
      'Founding-team MLE at an AI creative SaaS startup—LangGraph agents, ad pipelines, model scoring APIs, and the platform glue (Stripe, Meta, Shopify) that kept it all running.',
    details: [
      'Core product work on LangGraph: checkpointing, multi-turn flows, competitor analysis, product microsegmentation, and live market/social trend feeds for ad creation.',
      'Owned the ad-generation-to-publishing pipeline after a product pivot—AI image gen, variant editor with history, direct publish to Meta campaigns and ad sets.',
      "Productionized the research team's ad-scoring model into real-time API infrastructure (Node.js, AWS Lambda, typed contracts).",
      'Shipped 10+ workflows across 4 surfaces; owned 5+ integrations (Shopify, Meta, HubSpot, Stripe, Anrok).',
      'Cut recurring production incidents ~99% with validation, Sentry/PostHog, unit tests, and actually fixing root causes instead of patching symptoms.',
    ],
  },
  {
    id: 'bu-bmc',
    title: 'Research Scientist',
    subtitle: 'Boston University / Boston Medical Center',
    location: 'Boston, MA',
    period: 'Sep 2024 - Jun 2025',
    rating: 'Healthcare AI',
    tags: [
      'PyTorch',
      'CUDA',
      'Transformers',
      'LSTMs',
      'EEG',
      'Clinical AI',
      'Time Series',
      'Knowledge Graphs',
      'RAG',
      'PubMed',
      'Optuna',
      'HyperOpt',
    ],
    summary:
      'Three concurrent clinical AI projects at BU/BMC—EEG edema detection, meal-informed glucose modeling, and knowledge-graph RAG for medical literature—all under HIPAA-aware workflows.',
    details: [
      'EEG cerebral edema: Transformer/LSTM over 18 bipolar channels, 30-fold experiments, ~0.80 AUC at shorter horizons; also reported 92% test accuracy on held-out clinical data.',
      'Glucose modeling: built CGM prediction integrating meal intake for real-time glycemic trend forecasts—published in Circulation 2026.',
      'Knowledge graphs: PubMed-derived entity/subgraph retrieval to ground LLM clinical QA; explored GAN-based graph augmentation for data diversity.',
      'Mentored 7 grad researchers on clinical ML, data processing, and evaluation—learned that teaching forces you to know what you actually understand.',
      'GPU training on BU SCC with PyTorch/CUDA, mixed precision, Optuna/HyperOpt.',
    ],
  },
  {
    id: 'bespoke-care',
    title: 'Lead AI Engineer',
    subtitle: 'BeSpoke Care Inc., My Phoenyx',
    location: 'Boston, MA',
    period: 'Jun 2024 - Feb 2025',
    rating: 'Product AI',
    tags: [
      'My Phoenyx',
      'AutoGen',
      'Azure OpenAI',
      'FastAPI',
      'WebSockets',
      'Gemini',
      'GPT',
      'AWS Polly',
      'Dialogflow CX',
      'Ludwig',
      'AWS',
      'Raspberry Pi',
      'ESP32',
    ],
    summary:
      'Lead AI engineer for My Phoenyx—a bilingual learning companion for children. Multi-agent LLMs, voice AI, and deployment to 100+ smart devices.',
    details: [
      'Multi-agent architecture with AutoGen, Azure OpenAI, FastAPI, WebSockets; led 3-person team, +25% AI workflow throughput.',
      'Interactive storytelling with GPT-4o Mini, Gemini, AWS Polly, Dialogflow CX, and Ludwig—multilingual, age-adaptive content.',
      'Edge deployment: multithreaded AWS (EC2, Lambda) backend serving Raspberry Pi/ESP32 devices.',
      'Built CI/CD and code review practices for LLM apps—agents need the same engineering discipline as anything else in production.',
    ],
  },
  {
    id: 'time-machine-learning',
    title: 'AI Engineer',
    subtitle: 'Time Machine Learning Inc.',
    location: 'Boston, MA',
    period: 'Mar 2024 - Jun 2024',
    tags: ['RAG', 'Vector Search', 'Mistral', 'Azure MLOps', 'Python', 'SaaS'],
    summary:
      'Built the RAG and vector search backbone for a SaaS onboarding product—Mistral embeddings, Azure MLOps, and a 35% scalability bump.',
    details: [
      'Designed vector DB architecture with all-mpnet-base-v2 embeddings and retrieval-augmented onboarding flows.',
      'Stack: Mistral, Azure MLOps, FAISS-style vector search patterns.',
      'Short stint, but where I first connected RAG architecture to actual product onboarding—not just chatbot demos.',
    ],
  },
  {
    id: 'igs-nrel',
    title: 'Data Science Fellow',
    subtitle: 'Institute for Global Sustainability / NREL',
    location: 'Boston, MA',
    period: 'May 2023 - Jul 2023',
    tags: ['Python', 'scikit-learn', 'spaCy', 'Plotly', 'Data Science', 'Policy Analytics'],
    summary:
      'Energy policy data fellow with NREL advisors—RECS, Justice40, and LEAD datasets turned into 20+ Plotly dashboards for stakeholders.',
    details: [
      'Built an energy planning tool integrating RECS, Justice40, and LEAD data for sustainable policy analysis.',
      '20+ interactive Plotly Dash visualizations—designed for policymakers, not data scientists.',
      'Presented findings to 50+ stakeholders on energy inequality and justice implications.',
      'Python, scikit-learn, spaCy, regression/classification throughout.',
    ],
  },
  {
    id: 'bu-teaching-assistant',
    title: 'Teaching Assistant',
    subtitle: 'Boston University',
    location: 'Boston, MA',
    period: 'Jan 2023 - Dec 2023',
    tags: ['Teaching', 'Mentorship', 'AI', 'ML', 'Python', 'TensorFlow', 'NLP'],
    summary:
      'TA for Computational Tools for Data Science—30+ labs, 200+ students, and the satisfaction of watching someone finally get gradient descent.',
    details: [
      'Led weekly labs and office hours; taught Python, sklearn, TensorFlow, and PyTorch hands-on.',
      'Mentored 10+ BU Spark! NLP/ML projects; reviewed work on K-means, KNN, SVM, GMM, TF-IDF, Word2Vec, GANs.',
      '95% positive student evaluations—turns out showing up prepared and actually debugging their code matters.',
    ],
  },
  {
    id: 'ibm',
    title: 'SDE Intern',
    subtitle: 'IBM',
    location: 'Pune, India',
    period: 'Jan 2022 - Jul 2022',
    tags: ['Java', 'Quarkus', 'OpenJDK', 'Microservices', 'Backend Engineering'],
    summary:
      'IBM Security Verify microservice optimization—Quarkus migration that cut resource usage 50% and boosted efficiency 13%.',
    details: [
      'Migrated and optimized a Java microservice from legacy stack to Quarkus/OpenJDK 11.',
      'Coordinated with a cross-functional team in Singapore on IBM Security Verify upgrades.',
      'First taste of enterprise engineering: performance gains that actually showed up on customer invoices.',
    ],
  },
  {
    id: 'tech-mahindra',
    title: 'NLP Research Intern',
    subtitle: 'Tech Mahindra',
    location: 'Pune, India',
    period: 'Oct 2020 - Jan 2021',
    tags: ['NLP', 'Python', 'BeautifulSoup', 'NLTK', 'Multilingual AI'],
    summary:
      'Built a Sanskrit voice bot from scratch—web scraping 20+ sources, evaluating 11+ NLP algorithms, and caring about linguistic preservation.',
    details: [
      'Novel voice bot in Sanskrit: data from 20+ web sources, MySQL backend, BeautifulSoup/NLTK pipelines.',
      'Benchmarked 11+ algorithms for accuracy and scalability across multilingual workflows.',
      'Published in Wiley 2023—the project that convinced me NLP could preserve languages, not just automate them away.',
    ],
  },
];
