import type { ContentItem } from '../../types/content.ts';

export const skills: ContentItem[] = [
  {
    id: 'llm-agentic-systems',
    title: 'LLM and Agentic Systems',
    subtitle: 'Production model workflows',
    tags: [
      'LangGraph',
      'LangChain',
      'AutoGen',
      'RAG',
      'Multi-Agent Systems',
      'ReAct',
      'Tool Calling',
      'Prompt/Tool Design',
      'Guardrails',
      'Human-in-the-Loop Review',
      'LLM Evaluation',
      'GPT',
      'Gemini',
      'Mistral',
      'Azure OpenAI',
    ],
    summary:
      'The agent and LLM stack I reach for when building product features—not just notebooks.',
    details: [
      'LangGraph for stateful multi-turn flows; LangChain and AutoGen for agent orchestration.',
      'RAG, tool calling, ReAct patterns, guardrails, and human-in-the-loop review.',
      'Models: GPT, Gemini, Mistral, Azure OpenAI—with eval loops so you know when prompts drift.',
    ],
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    subtitle: 'Modeling, evaluation, and applied research',
    tags: [
      'PyTorch',
      'TensorFlow',
      'Keras',
      'Hugging Face Transformers',
      'CUDA',
      'NLP',
      'Computer Vision',
      'Time Series',
      'Vector Search',
      'Knowledge Graphs',
      'Model Evaluation',
      'Feature Engineering',
    ],
    summary:
      'From clinical EEG modeling to ISS geolocation—ML across NLP, CV, time series, and knowledge graphs.',
    details: [
      'PyTorch and TensorFlow for training; Hugging Face Transformers for NLP; CUDA for GPU work.',
      'Clinical time-series (EEG, CGM), computer vision, vector search, knowledge graphs.',
      'Care about evaluation methodology as much as model architecture—AUC without context is just a number.',
    ],
  },
  {
    id: 'engineering',
    title: 'Engineering',
    subtitle: 'Full-stack product and platform work',
    tags: [
      'Python',
      'TypeScript',
      'SQL',
      'FastAPI',
      'Node.js',
      'Next.js',
      'React',
      'REST APIs',
      'WebSockets',
      'OAuth 2.0',
      'RBAC',
      'Multi-Tenant SaaS',
      'Distributed Systems',
    ],
    summary:
      'Full-stack enough to own a feature end-to-end—frontend, API, auth, and the Postgres schema underneath.',
    details: [
      'Python and TypeScript as primary languages; FastAPI and Node.js for backends.',
      'Next.js/React frontends; REST and WebSockets; OAuth 2.0 and RBAC for multi-tenant SaaS.',
      "Comfortable debugging at any layer—because production bugs don't respect job titles.",
    ],
  },
  {
    id: 'data-infrastructure',
    title: 'Data and Infrastructure',
    subtitle: 'Storage, retrieval, cloud, and deployment',
    tags: [
      'Postgres',
      'Supabase',
      'FAISS',
      'ChromaDB',
      'Docker',
      'AWS',
      'Azure',
      'GCP',
      'Vercel',
      'AWS Lambda',
      'Inngest',
    ],
    summary:
      'Databases, vector stores, cloud, and the deployment plumbing that keeps models serving traffic.',
    details: [
      'Postgres/Supabase for relational data; FAISS and ChromaDB for vector retrieval.',
      'AWS, Azure, GCP, Vercel, Lambda, Inngest, Docker—pick the tool, not the hype.',
    ],
  },
  {
    id: 'product-reliability',
    title: 'Product Reliability',
    subtitle: 'Observability and workflow hardening',
    tags: [
      'Sentry',
      'PostHog',
      'CI/CD',
      'GitHub Actions',
      'MLOps',
      'Background Jobs',
      'Retry-Safe Ingestion',
      'Observability',
      'Analytics',
      'Testing',
    ],
    summary:
      'How I keep AI products from breaking silently—observability, testing, and retry-safe job design.',
    details: [
      'Sentry for errors, PostHog for product analytics, GitHub Actions for CI/CD.',
      'Background jobs with retry-safe ingestion; unit tests where they catch real regressions.',
      'Learned the hard way that an LLM feature without observability is a incident waiting to happen.',
    ],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    subtitle: 'Product and business systems',
    tags: ['Meta Marketing API', 'Shopify', 'HubSpot', 'Stripe', 'Anrok', 'SendGrid'],
    summary:
      "Third-party APIs I've wired into production—each one with its own auth dance and edge cases.",
    details: [
      'Meta Marketing API for ad publishing; Shopify and HubSpot for commerce/CRM.',
      'Stripe and Anrok for payments and tax; SendGrid for transactional email.',
      'Integration work is 20% API calls, 80% handling the weird failures.',
    ],
  },
];
